'use client'
import ExplorerPage from './explorer/page'
import WinPreviewGrid from './components/WinPreviewGrid'
import CardPreviewGrid from './components/CardPreviewGrid'
import StockPriceGrid from './components/StockPriceGrid'

export default function Home() {
  //     industryGroup: 'Retail (Special Lines)',
  //     primarySector: 'Consumer Discretionary',
  //     searchCountry: 'united states',
  //     searchName: '1-800-flowers.com, inc. (nasdaqgs:flws)',
  //     searchTicker: 'flws',
  //     sicCode: '5960',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'FLWS',
  //   },
  //   {
  //     broadGroup: 'United States',
  //     companyName: 'Apple Inc. (NasdaqGS:AAPL)',
  //     country: 'United States',
  //     exchange: 'NasdaqGS',
  //     industryGroup: 'Technology Hardware, Storage & Peripherals',
  //     primarySector: 'Information Technology',
  //     searchCountry: 'united states',
  //     searchName: 'apple inc. (nasdaqgs:aapl)',
  //     searchTicker: 'aapl',
  //     sicCode: '3571',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'AAPL',
  //   },
  //   {
  //     broadGroup: 'United States',
  //     companyName: 'Microsoft Corporation (NasdaqGS:MSFT)',
  //     country: 'United States',
  //     exchange: 'NasdaqGS',
  //     industryGroup: 'Systems Software',
  //     primarySector: 'Information Technology',
  //     searchCountry: 'united states',
  //     searchName: 'microsoft corporation (nasdaqgs:msft)',
  //     searchTicker: 'msft',
  //     sicCode: '7372',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'MSFT',
  //   },
  //   {
  //     broadGroup: 'United States',
  //     companyName: 'Amazon.com, Inc. (NasdaqGS:AMZN)',
  //     country: 'United States',
  //     exchange: 'NasdaqGS',
  //     industryGroup: 'Internet & Direct Marketing Retail',
  //     primarySector: 'Consumer Discretionary',
  //     searchCountry: 'united states',
  //     searchName: 'amazon.com, inc. (nasdaqgs:amzn)',
  //     searchTicker: 'amzn',
  //     sicCode: '5961',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'AMZN',
  //   },
  //   {
  //     broadGroup: 'United States',
  //     companyName: 'Alphabet Inc. (NasdaqGS:GOOGL)',
  //     country: 'United States',
  //     exchange: 'NasdaqGS',
  //     industryGroup: 'Interactive Media & Services',
  //     primarySector: 'Communication Services',
  //     searchCountry: 'united states',
  //     searchName: 'alphabet inc. (nasdaqgs:googl)',
  //     searchTicker: 'googl',
  //     sicCode: '7370',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'GOOGL',
  //   },
  //   {
  //     broadGroup: 'United States',
  //     companyName: 'Tesla, Inc. (NasdaqGS:TSLA)',
  //     country: 'United States',
  //     exchange: 'NasdaqGS',
  //     industryGroup: 'Automobile Manufacturers',
  //     primarySector: 'Consumer Discretionary',
  //     searchCountry: 'united states',
  //     searchName: 'tesla, inc. (nasdaqgs:tsla)',
  //     searchTicker: 'tsla',
  //     sicCode: '3711',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'TSLA',
  //   },
  //   {
  //     broadGroup: 'United States',
  //     companyName: 'Meta Platforms, Inc. (NasdaqGS:META)',
  //     country: 'United States',
  //     exchange: 'NasdaqGS',
  //     industryGroup: 'Interactive Media & Services',
  //     primarySector: 'Communication Services',
  //     searchCountry: 'united states',
  //     searchName: 'meta platforms, inc. (nasdaqgs:meta)',
  //     searchTicker: 'meta',
  //     sicCode: '7370',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'META',
  //   },
  //   {
  //     broadGroup: 'United States',
  //     companyName: 'NVIDIA Corporation (NasdaqGS:NVDA)',
  //     country: 'United States',
  //     exchange: 'NasdaqGS',
  //     industryGroup: 'Semiconductors',
  //     primarySector: 'Information Technology',
  //     searchCountry: 'united states',
  //     searchName: 'nvidia corporation (nasdaqgs:nvda)',
  //     searchTicker: 'nvda',
  //     sicCode: '3674',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'NVDA',
  //   },
  //   {
  //     broadGroup: 'United States',
  //     companyName: 'JPMorgan Chase & Co. (NYSE:JPM)',
  //     country: 'United States',
  //     exchange: 'NYSE',
  //     industryGroup: 'Diversified Banks',
  //     primarySector: 'Financials',
  //     searchCountry: 'united states',
  //     searchName: 'jpmorgan chase & co. (nyse:jpm)',
  //     searchTicker: 'jpm',
  //     sicCode: '6021',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'JPM',
  //   },
  //   {
  //     broadGroup: 'United States',
  //     companyName: 'The Coca-Cola Company (NYSE:KO)',
  //     country: 'United States',
  //     exchange: 'NYSE',
  //     industryGroup: 'Soft Drinks',
  //     primarySector: 'Consumer Staples',
  //     searchCountry: 'united states',
  //     searchName: 'the coca-cola company (nyse:ko)',
  //     searchTicker: 'ko',
  //     sicCode: '2086',
  //     source: 'Damodaran Global Equity Dataset',
  //     ticker: 'KO',
  //   },
  // ];

  // const centralBanks: CentralBankInfo[] = [
  //   {
  //     name: 'Federal Reserve System',
  //     country: 'United States',
  //     abbreviation: 'Fed',
  //     currentRate: '5.25-5.50%',
  //     lastChange: 'July 26, 2023 (+25bps)',
  //     nextMeeting: 'December 13, 2023',
  //     mandate: 'Maximum employment, stable prices, moderate long-term interest rates',
  //     governor: 'Jerome H. Powell',
  //     established: '1913',
  //     headquarters: 'Washington, D.C.',
  //     primaryObjective: 'Dual mandate: price stability and maximum employment',
  //     inflationTarget: '2% (PCE)',
  //     keyPolicies: [
  //       'Quantitative Easing/Tightening',
  //       'Forward Guidance',
  //       'Emergency Lending Facilities',
  //       'Regulatory Oversight'
  //     ],
  //     website: 'https://www.federalreserve.gov',
  //     discussionCount: 156,
  //     trendingTopics: ['Rate Hikes', 'Inflation', 'QE Tapering'],
  //     recentPosts: 23,
  //     sentiment: 'bearish' as const,
  //     marketImpact: 'High'
  //   },
  //   {
  //     name: 'European Central Bank',
  //     country: 'Eurozone',
  //     abbreviation: 'ECB',
  //     currentRate: '4.50% (Main Refinancing)',
  //     lastChange: 'September 14, 2023 (+25bps)',
  //     nextMeeting: 'December 14, 2023',
  //     mandate: 'Price stability in the euro area',
  //     governor: 'Christine Lagarde',
  //     established: '1998',
  //     headquarters: 'Frankfurt, Germany',
  //     primaryObjective: 'Price stability (inflation target)',
  //     inflationTarget: '2% (HICP)',
  //     keyPolicies: [
  //       'Asset Purchase Programme (APP)',
  //       'Targeted Longer-term Refinancing Operations (TLTRO)',
  //       'Forward Guidance',
  //       'Negative Interest Rate Policy'
  //     ],
  //     website: 'https://www.ecb.europa.eu',
  //     discussionCount: 89,
  //     trendingTopics: ['ECB Policy', 'Euro Inflation', 'Rate Decisions'],
  //     recentPosts: 15,
  //     sentiment: 'neutral' as const,
  //     marketImpact: 'Medium'
  //   },
  //   {
  //     name: 'Bank of England',
  //     country: 'United Kingdom',
  //     abbreviation: 'BoE',
  //     currentRate: '5.25%',
  //     lastChange: 'September 21, 2023 (No change)',
  //     nextMeeting: 'December 14, 2023',
  //     mandate: 'Monetary and financial stability',
  //     governor: 'Andrew Bailey',
  //     established: '1694',
  //     headquarters: 'London, England',
  //     primaryObjective: 'Price stability and supporting economic growth',
  //     inflationTarget: '2% (CPI)',
  //     keyPolicies: [
  //       'Quantitative Easing',
  //       'Forward Guidance',
  //       'Financial Stability',
  //       'Prudential Regulation'
  //     ],
  //     website: 'https://www.bankofengland.co.uk',
  //     discussionCount: 67,
  //     trendingTopics: ['BoE Policy', 'UK Inflation', 'Rate Pause'],
  //     recentPosts: 12,
  //     sentiment: 'neutral' as const,
  //     marketImpact: 'Medium'
  //   },
  //   {
  //     name: 'Bank of Japan',
  //     country: 'Japan',
  //     abbreviation: 'BoJ',
  //     currentRate: '-0.10%',
  //     lastChange: 'January 29, 2016 (-10bps)',
  //     nextMeeting: 'December 19, 2023',
  //     mandate: 'Price stability and financial system stability',
  //     governor: 'Kazuo Ueda',
  //     established: '1882',
  //     headquarters: 'Tokyo, Japan',
  //     primaryObjective: 'Price stability and economic growth',
  //     inflationTarget: '2% (CPI)',
  //     keyPolicies: [
  //       'Yield Curve Control (YCC)',
  //       'Quantitative and Qualitative Easing (QQE)',
  //       'Negative Interest Rate Policy',
  //       'Asset Purchase Programme'
  //     ],
  //     website: 'https://www.boj.or.jp',
  //     discussionCount: 45,
  //     trendingTopics: ['YCC Policy', 'Negative Rates', 'Yen Weakness'],
  //     recentPosts: 8,
  //     sentiment: 'bullish' as const,
  //     marketImpact: 'High'
  //   },
  //   {
  //     name: 'People\'s Bank of China',
  //     country: 'China',
  //     abbreviation: 'PBoC',
  //     currentRate: '3.45% (1-year LPR)',
  //     lastChange: 'August 21, 2023 (-15bps)',
  //     nextMeeting: 'December 20, 2023',
  //     mandate: 'Monetary policy and financial stability',
  //     governor: 'Pan Gongsheng',
  //     established: '1948',
  //     headquarters: 'Beijing, China',
  //     primaryObjective: 'Price stability and economic growth',
  //     inflationTarget: '3% (CPI)',
  //     keyPolicies: [
  //       'Loan Prime Rate (LPR) Reform',
  //       'Reserve Requirement Ratio (RRR)',
  //       'Open Market Operations',
  //       'Macroprudential Policy'
  //     ],
  //     website: 'https://www.pbc.gov.cn',
  //     discussionCount: 78,
  //     trendingTopics: ['LPR Cuts', 'Property Market', 'Economic Stimulus'],
  //     recentPosts: 19,
  //     sentiment: 'bullish' as const,
  //     marketImpact: 'High'
  //   },
  //   {
  //     name: 'Bank of Canada',
  //     country: 'Canada',
  //     abbreviation: 'BoC',
  //     currentRate: '5.00%',
  //     lastChange: 'July 12, 2023 (+25bps)',
  //     nextMeeting: 'December 6, 2023',
  //     mandate: 'Low, stable and predictable inflation',
  //     governor: 'Tiff Macklem',
  //     established: '1935',
  //     headquarters: 'Ottawa, Canada',
  //     primaryObjective: 'Price stability and economic growth',
  //     inflationTarget: '2% (CPI)',
  //     keyPolicies: [
  //       'Inflation Targeting',
  //       'Forward Guidance',
  //       'Quantitative Easing',
  //       'Financial System Stability'
  //     ],
  //     website: 'https://www.bankofcanada.ca',
  //     discussionCount: 34,
  //     trendingTopics: ['BoC Policy', 'Canadian Inflation', 'Rate Decisions'],
  //     recentPosts: 6,
  //     sentiment: 'neutral' as const,
  //     marketImpact: 'Medium'
  //   },
  //   {
  //     name: 'Reserve Bank of Australia',
  //     country: 'Australia',
  //     abbreviation: 'RBA',
  //     currentRate: '4.35%',
  //     lastChange: 'November 7, 2023 (+25bps)',
  //     nextMeeting: 'December 5, 2023',
  //     mandate: 'Price stability, full employment, economic prosperity',
  //     governor: 'Michele Bullock',
  //     established: '1960',
  //     headquarters: 'Sydney, Australia',
  //     primaryObjective: 'Price stability and full employment',
  //     inflationTarget: '2-3% (CPI)',
  //     keyPolicies: [
  //       'Inflation Targeting',
  //       'Forward Guidance',
  //       'Quantitative Easing',
  //       'Financial Stability'
  //     ],
  //     website: 'https://www.rba.gov.au',
  //     discussionCount: 28,
  //     trendingTopics: ['RBA Policy', 'Australian Inflation', 'Rate Hikes'],
  //     recentPosts: 5,
  //     sentiment: 'bearish' as const,
  //     marketImpact: 'Medium'
  //   },
  //   {
  //     name: 'Reserve Bank of India',
  //     country: 'India',
  //     abbreviation: 'RBI',
  //     currentRate: '6.50%',
  //     lastChange: 'February 8, 2023 (+25bps)',
  //     nextMeeting: 'December 8, 2023',
  //     mandate: 'Price stability and economic growth',
  //     governor: 'Shaktikanta Das',
  //     established: '1935',
  //     headquarters: 'Mumbai, India',
  //     primaryObjective: 'Price stability and economic growth',
  //     inflationTarget: '4% ± 2% (CPI)',
  //     keyPolicies: [
  //       'Inflation Targeting',
  //       'Liquidity Management',
  //       'Foreign Exchange Management',
  //       'Financial Stability'
  //     ],
  //     website: 'https://www.rbi.org.in',
  //     discussionCount: 42,
  //     trendingTopics: ['RBI Policy', 'Indian Inflation', 'Rate Decisions'],
  //     recentPosts: 9,
  //     sentiment: 'neutral' as const,
  //     marketImpact: 'Medium'
  //   },
  //   {
  //     name: 'Swiss National Bank',
  //     country: 'Switzerland',
  //     abbreviation: 'SNB',
  //     currentRate: '1.75%',
  //     lastChange: 'September 21, 2023 (+25bps)',
  //     nextMeeting: 'December 14, 2023',
  //     mandate: 'Price stability and financial stability',
  //     governor: 'Thomas Jordan',
  //     established: '1907',
  //     headquarters: 'Bern, Switzerland',
  //     primaryObjective: 'Price stability',
  //     inflationTarget: '2% (CPI)',
  //     keyPolicies: [
  //       'Inflation Targeting',
  //       'Foreign Exchange Interventions',
  //       'Negative Interest Rates',
  //       'Financial Stability'
  //     ],
  //     website: 'https://www.snb.ch',
  //     discussionCount: 23,
  //     trendingTopics: ['SNB Policy', 'Swiss Franc', 'Rate Decisions'],
  //     recentPosts: 4,
  //     sentiment: 'neutral' as const,
  //     marketImpact: 'Low'
  //   },
  //   {
  //     name: 'Sveriges Riksbank',
  //     country: 'Sweden',
  //     abbreviation: 'Riksbank',
  //     currentRate: '4.00%',
  //     lastChange: 'September 20, 2023 (+25bps)',
  //     nextMeeting: 'December 20, 2023',
  //     mandate: 'Price stability and financial stability',
  //     governor: 'Erik Thedéen',
  //     established: '1668',
  //     headquarters: 'Stockholm, Sweden',
  //     primaryObjective: 'Price stability',
  //     inflationTarget: '2% (CPI)',
  //     keyPolicies: [
  //       'Inflation Targeting',
  //       'Negative Interest Rates',
  //       'Asset Purchase Programme',
  //       'Financial Stability'
  //     ],
  //     website: 'https://www.riksbank.se',
  //     discussionCount: 18,
  //     trendingTopics: ['Riksbank Policy', 'Swedish Inflation', 'Rate Decisions'],
  //     recentPosts: 3,
  //     sentiment: 'neutral' as const,
  //     marketImpact: 'Low'
  //   }
  // ];
  return (
    <main className="flex flex-col items-center justify-center min-h-screen text-center">
      <ExplorerPage />

      <CardPreviewGrid />
      <WinPreviewGrid />
    </main>
  )
}
