import { ChronologyCardHydrated } from '../components/ChronologyCard'
export const sampleChronologyCards: ChronologyCardHydrated[] = [
  {
    id: 'chrono-001',
    name: 'The Rise and Fall of Rome',
    description:
      'A comprehensive timeline tracking the Roman Empire from its founding in 753 BCE through its collapse in 476 CE, including major battles, emperors, and cultural milestones.',
    createdAt: Date.now() - 86400000 * 7, // 7 days ago
    createdBy: 'user-rome-historian',
    categories: ['History', 'Ancient Civilizations', 'Europe'],
    likeCount: 1247,
    saveCount: 892,
    sharedCount: 234,
    hitCount: 15420,
    repostCount: 156,
    stats: {
      winsCount: 23,
      totalUpvotes: 3421,
      totalViews: 15420,
      totalCelebrations: 189,
      totalComments: 456,
      lastWinAt: Date.now() - 86400000 * 2,
    },
    creator: {
      display: 'HistoryBuff_92',
      pfp: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rome',
    },
    previewMedia: [
      'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
      'https://images.unsplash.com/photo-1531572753322-ad063cecc140',
      'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
    ],
    savedByUser: true,
    likedByUser: true,
    repostedByUser: false,
  },
  {
    id: 'chrono-002',
    name: 'Evolution of the iPhone',
    description:
      'From the original iPhone in 2007 to the latest models, tracking every release, feature update, and technological breakthrough.',
    createdAt: Date.now() - 86400000 * 3, // 3 days ago
    createdBy: 'user-tech-enthusiast',
    categories: ['Technology', 'Mobile', 'Apple', 'Innovation'],
    likeCount: 3421,
    saveCount: 2103,
    sharedCount: 891,
    hitCount: 45230,
    repostCount: 567,
    stats: {
      winsCount: 45,
      totalUpvotes: 8932,
      totalViews: 45230,
      totalCelebrations: 412,
      totalComments: 1203,
      lastWinAt: Date.now() - 86400000,
    },
    creator: {
      display: 'TechTimeline',
      pfp: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tech',
    },
    previewMedia: ['https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5'],
    savedByUser: false,
    likedByUser: true,
    repostedByUser: true,
  },
  {
    id: 'chrono-003',
    name: 'Climate Change: Key Events',
    description:
      'Major scientific discoveries, international agreements, and environmental milestones in understanding and addressing climate change.',
    createdAt: Date.now() - 86400000 * 14, // 14 days ago
    createdBy: 'user-climate-scientist',
    categories: ['Environment', 'Science', 'Climate', 'Global Affairs'],
    likeCount: 892,
    saveCount: 1456,
    sharedCount: 423,
    hitCount: 23400,
    repostCount: 234,
    stats: {
      winsCount: 12,
      totalUpvotes: 2341,
      totalViews: 23400,
      totalCelebrations: 145,
      totalComments: 678,
      lastWinAt: Date.now() - 86400000 * 5,
    },
    creator: {
      display: 'Dr. EarthWatch',
      pfp: 'https://api.dicebear.com/7.x/avataaars/svg?seed=climate',
    },
    previewMedia: [
      'https://images.unsplash.com/photo-1569163139394-de4798aa62b6',
      'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce',
    ],
    savedByUser: true,
    likedByUser: false,
    repostedByUser: false,
  },
  {
    id: 'chrono-004',
    name: 'Marvel Cinematic Universe',
    description:
      'Every MCU film and TV show in chronological order, from Captain America: The First Avenger to the latest releases.',
    createdAt: Date.now() - 86400000 * 1, // 1 day ago
    createdBy: 'user-marvel-fan',
    categories: ['Entertainment', 'Movies', 'Marvel', 'Pop Culture'],
    likeCount: 5678,
    saveCount: 3421,
    sharedCount: 1234,
    hitCount: 67890,
    repostCount: 891,
    stats: {
      winsCount: 67,
      totalUpvotes: 12456,
      totalViews: 67890,
      totalCelebrations: 789,
      totalComments: 2341,
      lastWinAt: Date.now() - 3600000, // 1 hour ago
    },
    creator: {
      display: 'MCU_Chronologist',
      pfp: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marvel',
    },
    previewMedia: [
      'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0',
      'https://images.unsplash.com/photo-1608889335941-32ac5f2041b9',
      'https://images.unsplash.com/photo-1635805737707-575885ab0820',
    ],
    savedByUser: false,
    likedByUser: false,
    repostedByUser: false,
  },
  {
    id: 'chrono-005',
    name: 'History of Jazz Music',
    description:
      'From New Orleans origins to modern fusion, tracking the evolution of jazz through its legendary artists and groundbreaking albums.',
    createdAt: Date.now() - 86400000 * 21, // 21 days ago
    createdBy: 'user-jazz-lover',
    categories: ['Music', 'Jazz', 'Culture', 'History'],
    likeCount: 423,
    saveCount: 567,
    sharedCount: 89,
    hitCount: 8900,
    repostCount: 45,
    stats: {
      winsCount: 8,
      totalUpvotes: 891,
      totalViews: 8900,
      totalCelebrations: 67,
      totalComments: 234,
      lastWinAt: Date.now() - 86400000 * 8,
    },
    creator: {
      display: 'JazzHistorian',
      pfp: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jazz',
    },
    previewMedia: ['https://images.unsplash.com/photo-1511192336575-5a79af67a629'],
    savedByUser: true,
    likedByUser: true,
    repostedByUser: false,
  },
  {
    id: 'chrono-006',
    name: 'Space Exploration Milestones',
    description:
      "Humanity's journey to the stars: from Sputnik to Mars rovers, tracking every major achievement in space exploration.",
    createdAt: Date.now() - 86400000 * 30, // 30 days ago
    createdBy: 'user-space-enthusiast',
    categories: ['Space', 'Science', 'Technology', 'Exploration'],
    likeCount: 2103,
    saveCount: 1678,
    sharedCount: 456,
    hitCount: 34560,
    repostCount: 312,
    stats: {
      winsCount: 34,
      totalUpvotes: 5432,
      totalViews: 34560,
      totalCelebrations: 298,
      totalComments: 987,
      lastWinAt: Date.now() - 86400000 * 3,
    },
    creator: {
      display: 'CosmicChronology',
      pfp: 'https://api.dicebear.com/7.x/avataaars/svg?seed=space',
    },
    previewMedia: [
      'https://images.unsplash.com/photo-1446776653964-20c1d3a81b06',
      'https://images.unsplash.com/photo-1614732414444-096e5f1122d5',
    ],
    savedByUser: false,
    likedByUser: true,
    repostedByUser: false,
  },
  {
    id: 'chrono-007',
    name: 'My Personal Fitness Journey',
    description:
      'Documenting my transformation from couch potato to marathon runner, including workouts, diet changes, and race results.',
    createdAt: Date.now() - 86400000 * 2, // 2 days ago
    createdBy: 'user-fitness-newbie',
    categories: ['Fitness', 'Personal', 'Health', 'Motivation'],
    likeCount: 156,
    saveCount: 89,
    sharedCount: 23,
    hitCount: 1234,
    repostCount: 12,
    stats: {
      winsCount: 3,
      totalUpvotes: 245,
      totalViews: 1234,
      totalCelebrations: 34,
      totalComments: 67,
      lastWinAt: Date.now() - 86400000 * 1,
    },
    creator: {
      display: 'RunningTowardsBetter',
      pfp: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fitness',
    },
    previewMedia: [],
    savedByUser: false,
    likedByUser: false,
    repostedByUser: false,
  },
  {
    id: 'chrono-008',
    name: 'Bitcoin Price History',
    description:
      "Tracking Bitcoin's volatile journey from pennies to thousands, including major crashes, bull runs, and regulatory events.",
    createdAt: Date.now() - 86400000 * 45, // 45 days ago
    createdBy: 'user-crypto-analyst',
    categories: ['Cryptocurrency', 'Finance', 'Bitcoin', 'Investment'],
    likeCount: 3241,
    saveCount: 2987,
    sharedCount: 1567,
    hitCount: 78900,
    repostCount: 1234,
    stats: {
      winsCount: 56,
      totalUpvotes: 9876,
      totalViews: 78900,
      totalCelebrations: 567,
      totalComments: 3456,
      lastWinAt: Date.now() - 86400000 * 2,
    },
    creator: {
      display: 'CryptoChronos',
      pfp: 'https://api.dicebear.com/7.x/avataaars/svg?seed=crypto',
    },
    previewMedia: ['https://images.unsplash.com/photo-1621416894569-0f39ed31d247'],
    savedByUser: true,
    likedByUser: true,
    repostedByUser: true,
  },
]

// Edge case: minimal data
export const minimalChronologyCard: ChronologyCardHydrated = {
  id: 'chrono-minimal',
  name: 'Test Timeline',
  description: 'A basic timeline for testing minimal data display',
  createdAt: Date.now(),
  createdBy: 'user-test',
  categories: [],
  likeCount: 0,
  saveCount: 0,
  sharedCount: 0,
  hitCount: 0,
  repostCount: 0,
}

// Edge case: very long content
export const longContentChronologyCard: ChronologyCardHydrated = {
  id: 'chrono-long',
  name: 'The Complete and Exhaustive History of Everything That Ever Happened in the Entire Universe',
  description:
    'This is an extremely long description that goes on and on and on, describing every single detail about the timeline in excruciating detail. It includes information about the big bang, the formation of galaxies, the evolution of life on Earth, the rise and fall of civilizations, technological advancements, cultural movements, and everything in between. This description is intentionally verbose to test how the card handles very long text content.',
  createdAt: Date.now() - 86400000 * 100,
  createdBy: 'user-verbose',
  categories: [
    'Everything',
    'History',
    'Science',
    'Philosophy',
    'Culture',
    'Technology',
    'Nature',
    'Space',
  ],
  likeCount: 999999,
  saveCount: 888888,
  sharedCount: 777777,
  hitCount: 9999999,
  repostCount: 666666,
  stats: {
    winsCount: 999,
    totalUpvotes: 999999,
    totalViews: 9999999,
    totalCelebrations: 99999,
    totalComments: 99999,
    lastWinAt: Date.now(),
  },
  creator: {
    display: 'TheUltimateChronologistWithAReallyLongUsername',
    pfp: 'https://api.dicebear.com/7.x/avataaars/svg?seed=long',
  },
  previewMedia: Array(10).fill('https://images.unsplash.com/photo-1451187580459-43490279c0fa'),
  savedByUser: true,
  likedByUser: true,
  repostedByUser: true,
}
