import { WinProps } from '../components/WinCard'

export const sampleWins: WinProps['win'][] = [
  {
    id: '1',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    title: 'Prithvi Narayan Shah Divya Upadesh',
    paragraphs: [
      'After His Majesty captured the three cities of Nepal (Kathmandu, Lalitput and Bhaktapur) and the Hindupati Raja,l he went to Nuwakot for the last. He summoned his priests, teachers, household,4 family, nobles, and his tutor, Surath Singh Rana, and all the elders and spoke to them thus : When an old man dies, his words die with him, so they say. What vou who are gathered here will hear from me, pass on to your children, and they to ours; and this kingdom will endure.',
    ],
    upvotes: 342,
    previewImageUrl: '',
    commentCount: 78,
  },
  {
    id: '2',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    title: 'When an old man dies, his word dies with him',
    paragraphs: [
      'So they say. What vou who are gathered here will hear from me, pass on to your children, and they to ours; and this kingdom will endure.',
    ],
    upvotes: 892,
    commentCount: 234,
  },
  {
    id: '3',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    title: 'Avatars of the Pandavs',
    paragraphs: [
      'Our mothers were three. Of three bridal chambers we brothers came, avatars of the Pandavs. Mv own marriage took place in Makwanpur. The bride was not given to me. I went to Makwanpur to take the bride and return by way of Nepal (Nepal pani dekhi bhani au bhani).',
    ],
    upvotes: 567,
    previewImageUrl: '',
    commentCount: 89,
  },
  {
    id: '4',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    title: 'The Marriage of Prithvi Narayan Shah',
    paragraphs: [
      ' Then I arrived, I said to Dikbhanda Sen: " If vou will give me the one-tusked elephant and the nine lakh necklacela I will take the bride. If you refuse, I will take her and cut my way through with the sword."',
    ],
    upvotes: 1203,
    previewImageUrl: '',
    commentCount: 156,
  },
  {
    id: '5',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    title: 'Which is Nepal?',
    paragraphs: [
      "Threats were made. That the king of Nepal might not recognize me and seize me, I covered my shoulders with a ghume and moved up the banks of the Rapti. Companions to me were Bhanu Jyotisi, Kulananda Jyotisi, and others of my family. From Chandragiri's top I asked, 'Which is Nepal ?'",
    ],
    upvotes: 445,
    commentCount: 92,
  },
  {
    id: '6',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    title: 'They showed me, saying',
    paragraphs: [
      'That is Bhadgaon, that is Patan, and there lies Kathmandu. The thought came to my heart that if I might be king of these three cities, why, let it be so. At this same time these two astrologers said to me, “O King, your heart is melting with desire." I was struck with wonder.',
    ],
    upvotes: 2341,
    commentCount: 412,
  },
  {
    id: '7',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    title: 'How did they know my inmost thoughts and so speak to me ? ',
    paragraphs: [
      'At the moment your gaze rested on Nepal (Nepalma) you stroked your moustache and in your heart you longed to be lting of Nepal, as it seemed to us." " Will this come to pass ?"',
    ],
    upvotes: 678,
    previewImageUrl: '',
    commentCount: 134,
  },
  {
    id: '8',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    title: 'Vision laid to Planning - The Great King',
    paragraphs: [
      'I (Prithvi Narayan Shah asked. " You, O Prince, have held at all times great respect for cows, Brahmins, guests, holy men, the gods, and goddesses. Also, in our hands lies the blessing of Saraswati. You will one day be king of Nepal."',
    ],
    upvotes: 534,
    commentCount: 167,
  },
  {
    id: '9',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    title: 'The king counts his men',
    paragraphs: [
      'And I said: " Bevond Thankot`s great pass, a day and a night beyond Kalleri Ghat, up Dhading and beyond Champabati River, under the protecting arms of Ligligkot, I have three men. Jyotisi, send a letter to call them." " Their names ?" he asked. " Ranjit Basnyet,"',
    ],
    upvotes: 289,
    previewImageUrl: '',
    commentCount: 45,
  },
  {
    id: '10',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    title: 'Come straightway, without sleeping, to Maidhi',
    paragraphs: [
      'I said, " Man Singh Rokaya, Birbhadra Pathak." " Come straightway, without sleeping, to Maidhi," I wrote. And they came. I spoke privately to these three. " I have exchanged threats with Dikbhanda Sen ; I have come to Nepal and have seen it. And I have decided it must be mine.',
    ],
    upvotes: 892,
    previewImageUrl: '',
    commentCount: 201,
  },
  {
    id: '11',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    title: 'What say you, O my counsel?',
    paragraphs: [
      '" Attack, O Prince," they said. And they agreed with me. ButI asked them, " If I go to seize another`s kingdom, will not another come to seize my kingdom ?"',
    ],
    upvotes: 743,
    commentCount: 178,
  },
  {
    id: '12',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    title: 'Yours is the voice to frighten the elephants',
    paragraphs: [
      '" Yours, 0 Prince, is the voice to frighten elephants. If those Baisi and Chaubisi princes come, a river of blood will flow in the Chepa," they answered. We rose from our secret place and went to Gorkha. My unclel had taken the Deoghat road to have darshan of Nilakantha & Pashupati.',
    ],
    upvotes: 456,
    previewImageUrl: '',
    commentCount: 98,
  },
  {
    id: '13',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    title: 'Consultations and Planning',
    paragraphs: [
      'After having darshan of Nilkuntha and Pasupati, he came to Gorkha to have darshan of Gorkhanath. After his worship, he met me. And I said: " Uncle, I have gone to Makwanpur. I reached Nepal and saw that kingdom. I have decided I must attack that kingdom." ',
    ],
    previewImageUrl: '',
    upvotes: 512,
    commentCount: 87,
  },
  {
    id: '14',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
    title: 'What must I do to succeed ? Instruct me, if you will',
    paragraphs: [
      'And he answered: " At the time of Panchuratri I had a dream. There was a great war in which there were five men, avatars of the Pandavs, as it were. Without war Nepal will not be conquered. Lamjung is called a Garud. Gorkha is called a snake. Nepal, a frog. The Snake must deceive the eyes of the Garud, and then it can eat the frog."',
    ],
    upvotes: 1124,
    previewImageUrl: '',
    commentCount: 267,
  },
  {
    id: '15',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(),
    title: 'The 4 Clans',
    paragraphs: [
      '" I have,” I said, " four clans of warriors. Which of these must go, if the work is to be finished quickly ?" " Which are the clans ?" I asked. " Brahmin, Khas, Magar, Thakuri," I said. " Which of these should go to finish the task quickly ?"',
    ],
    upvotes: 678,
    previewImageUrl: '',
    commentCount: 143,
  },
  {
    id: '16',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 216).toISOString(),
    title: 'The Brahmins, Khas, Magar, Thakuri',
    paragraphs: [
      '"The Brahmin goes as a bullock," he said; " if he goes, it will be sin everywhere. The Thakuri goes as a lion; afterwards comes his craft. The Magar goes as a mountain pony. He will be slow. The Khas goes as a swift Arabian steed. If the Khas goes, it will be quickly done, or so it seems to me."',
    ],
    upvotes: 934,
    commentCount: 189,
  },
  {
    id: '17',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 240).toISOString(),
    title: 'Meeting the King of Lamjung',
    paragraphs: [
      'And with this he gave me much other advice. I took his advice, and then I went to meet the king of Lamjung, Ripurnardan Shah. We met at Chepe Ghat. We spoke of a treaty and of home affairs. The matter for which we would agree to conclude a treaty was as a knot in my heart.',
    ],
    upvotes: 1456,
    commentCount: 312,
  },
  {
    id: '18',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 264).toISOString(),
    title: 'This thing Kalu Pande did.',
    paragraphs: [
      'And the treaty was strong and lasting. And I was in wonder. But I was also pleased. He, with whom the people are pleased, he it is who is made kazi, so the Shahtra say. I consulted the wishes of the people and found that the people also wanted him.',
    ],
    upvotes: 423,
    previewImageUrl: '',
    commentCount: 76,
  },
  {
    id: '19',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 288).toISOString(),
    title: 'And Kalu Pande is made the Kazi',
    paragraphs: [
      'If Kalu Pande is made kazi, all the people will be pleased, I was advised. Then I looked to the Baisi and the Chaubise princes. And they told me that if Kalu Pande were made kazi, the home and foreign policy would be strong. ',
    ],
    upvotes: 687,
    commentCount: 134,
  },
  {
    id: '20',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 312).toISOString(),
    title: 'It was in my mind to make Biraj Bakheti kazi.',
    paragraphs: [
      'But Kalu Pande was thought to be wiser, and Kalu Pande was made kazi. Now I made a marriage bond between the Pandes and the Basnyets. " Give your daughter to the son of Shivaram Basnyet, Kehe Singh Basnyet," I said. ',
    ],
    upvotes: 789,
    previewImageUrl: '',
    commentCount: 167,
  },
  {
    id: '21',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 336).toISOString(),
    title: 'And I married them and made the bond between the Pandes and the Basnyets.',
    paragraphs: [
      'I made a Pande the shield (foreign policy) and a Basnyet the sword (war minister) and prepared to ascend to Nepal.',
    ],
    upvotes: 545,
    commentCount: 112,
  },
]
