import { WinProps } from '../components/WinCard'

export const sampleWins: WinProps['win'][] = [
  {
    id: '1',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    title: 'Prithvi Narayan Shah Divya Upadesh',
    paragraphs: [
      'After His Majesty captured the three cities of Nepal (Kathmandu, Lalitput and Bhaktapur) and the Hindupati Raja,l he went to Nuwakot for the last. He summoned his priests, teachers, household,4 family, nobles, and his tutor, Surath Singh Rana, and all the elders and spoke to them thus : When an old man dies, his words die with him, so they say. What vou who are gathered here will hear from me, pass on to your children, and they to ours; and this kingdom will endure.',
    ],
    upvotes: 342,
    previewImageUrl: '',
    commentCount: 78,
  },
  {
    id: '2',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    title: 'When an old man dies, his word dies with him',
    paragraphs: [
      'So they say. What vou who are gathered here will hear from me, pass on to your children, and they to ours; and this kingdom will endure.',
    ],
    upvotes: 892,
    commentCount: 234,
  },
  {
    id: '3',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    title: 'Avatars of the Pandavs',
    paragraphs: [
      'Our mothers were three. Of three bridal chambers we brothers came, avatars of the Pandavs. Mv own marriage took place in Makwanpur. The bride was not given to me. I went to Makwanpur to take the bride and return by way of Nepal (Nepal pani dekhi bhani au bhani).',
    ],
    upvotes: 567,
    previewImageUrl: '',
    commentCount: 89,
  },
  {
    id: '4',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    title: 'The Marriage of Prithvi Narayan Shah',
    paragraphs: [
      ' Then I arrived, I said to Dikbhanda Sen: " If vou will give me the one-tusked elephant and the nine lakh necklacela I will take the bride. If you refuse, I will take her and cut my way through with the sword."',
    ],
    upvotes: 1203,
    previewImageUrl: '',
    commentCount: 156,
  },
  {
    id: '5',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    title: 'Which is Nepal?',
    paragraphs: [
      "Threats were made. That the king of Nepal might not recognize me and seize me, I covered my shoulders with a ghume and moved up the banks of the Rapti. Companions to me were Bhanu Jyotisi, Kulananda Jyotisi, and others of my family. From Chandragiri's top I asked, 'Which is Nepal ?'",
    ],
    upvotes: 445,
    commentCount: 92,
  },
  {
    id: '6',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    title: 'They showed me, saying',
    paragraphs: [
      'That is Bhadgaon, that is Patan, and there lies Kathmandu. The thought came to my heart that if I might be king of these three cities, why, let it be so. At this same time these two astrologers said to me, “O King, your heart is melting with desire." I was struck with wonder.',
    ],
    upvotes: 2341,
    commentCount: 412,
  },
  {
    id: '7',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    title: 'How did they know my inmost thoughts and so speak to me ? ',
    paragraphs: [
      'At the moment your gaze rested on Nepal (Nepalma) you stroked your moustache and in your heart you longed to be lting of Nepal, as it seemed to us." " Will this come to pass ?"',
    ],
    upvotes: 678,
    previewImageUrl: '',
    commentCount: 134,
  },
  {
    id: '8',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    title: 'Vision laid to Planning - The Great King',
    paragraphs: [
      'I (Prithvi Narayan Shah asked. " You, O Prince, have held at all times great respect for cows, Brahmins, guests, holy men, the gods, and goddesses. Also, in our hands lies the blessing of Saraswati. You will one day be king of Nepal."',
    ],
    upvotes: 534,
    commentCount: 167,
  },
  {
    id: '9',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    title: 'The king counts his men',
    paragraphs: [
      'And I said: " Bevond Thankot`s great pass, a day and a night beyond Kalleri Ghat, up Dhading and beyond Champabati River, under the protecting arms of Ligligkot, I have three men. Jyotisi, send a letter to call them." " Their names ?" he asked. " Ranjit Basnyet,"',
    ],
    upvotes: 289,
    previewImageUrl: '',
    commentCount: 45,
  },
  {
    id: '10',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    title: 'Come straightway, without sleeping, to Maidhi',
    paragraphs: [
      'I said, " Man Singh Rokaya, Birbhadra Pathak." " Come straightway, without sleeping, to Maidhi," I wrote. And they came. I spoke privately to these three. " I have exchanged threats with Dikbhanda Sen ; I have come to Nepal and have seen it. And I have decided it must be mine.',
    ],
    upvotes: 892,
    previewImageUrl: '',
    commentCount: 201,
  },
  {
    id: '11',
    username: 'ml_engineer_bangalore',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    title: 'What say you, O my counsel?',
    paragraphs: [
      'What say you ?" " Attack, O Prince," they said.',
      'Released everything under MIT license. Language preservation through technology. Communities are already using it to digitize oral histories.',
    ],
    upvotes: 743,
    commentCount: 178,
  },
  {
    id: '12',
    username: 'urban_planner_amsterdam',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    title: 'City approved my car-free neighborhood design',
    paragraphs: [
      'Took 4 years of community meetings and revisions. We are creating a 15-minute neighborhood where everything is walkable.',
      'Construction starts next month. This will be a model for other cities rethinking urban spaces around people instead of cars.',
    ],
    upvotes: 456,
    previewImageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400',
    commentCount: 98,
  },
  {
    id: '13',
    username: 'jazz_composer_new_orleans',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    title: 'My album blending jazz and West African rhythms won a Grammy',
    paragraphs: [
      'Spent 2 years in Senegal learning traditional drumming and collaborating with local musicians.',
      'This music is about diaspora and connection. The Grammy is validation but the real win was the creative journey and friendships formed.',
    ],
    upvotes: 512,
    commentCount: 87,
  },
  {
    id: '14',
    username: 'ocean_scientist_australia',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
    title: 'Discovered coral species that resists bleaching',
    paragraphs: [
      'After 200 dives mapping the Great Barrier Reef, we found colonies thriving in warming waters.',
      'Their genetic adaptation could be key to reef restoration. We are already testing propagation methods. There is still hope for our reefs.',
    ],
    upvotes: 1124,
    previewImageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400',
    commentCount: 267,
  },
  {
    id: '15',
    username: 'vr_designer_singapore',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(),
    title: 'Created VR therapy program that reduces PTSD symptoms by 60%',
    paragraphs: [
      'Worked with psychologists and veterans to design safe exposure therapy in virtual environments.',
      'Clinical trials showed better results than traditional methods. Now partnering with VA hospitals to scale this up.',
    ],
    upvotes: 678,
    commentCount: 143,
  },
  {
    id: '16',
    username: 'indigenous_language_teacher',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 216).toISOString(),
    title: 'First native speaker graduated from our language immersion program',
    paragraphs: [
      'My language had only 12 fluent speakers left. We started teaching children 5 years ago.',
      'Today our first student became fluent. She is 14 and already teaching her younger siblings. A language survives.',
    ],
    upvotes: 934,
    commentCount: 189,
  },
  {
    id: '17',
    username: 'space_engineer_mumbai',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 240).toISOString(),
    title: 'Our satellite constellation brings internet to remote villages',
    paragraphs: [
      'Launched the last of 48 satellites yesterday. Now covering regions where fiber optic is impossible.',
      '500 million people will gain internet access. Education and economic opportunity following connectivity.',
    ],
    upvotes: 1456,
    commentCount: 312,
  },
  {
    id: '18',
    username: 'textile_artist_ghana',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 264).toISOString(),
    title: 'My kente patterns are in Victoria and Albert Museum',
    paragraphs: [
      'Modern interpretations of traditional Ashanti weaving. Each pattern tells stories of resistance and resilience.',
      'The museum specifically wanted contemporary African voices. Our craft traditions are living art, not artifacts.',
    ],
    upvotes: 423,
    previewImageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400',
    commentCount: 76,
  },
  {
    id: '19',
    username: 'robotics_professor_zurich',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 288).toISOString(),
    title: 'Our soft robots can safely interact with marine life',
    paragraphs: [
      'Developed bio-inspired underwater drones that move like jellyfish. No propellers to harm wildlife.',
      'Already deployed to study deep sea creatures without disturbing them. Nature-inspired engineering at its best.',
    ],
    upvotes: 687,
    commentCount: 134,
  },
  {
    id: '20',
    username: 'community_organizer_detroit',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 312).toISOString(),
    title: 'Our urban farm collective feeds 2,000 families',
    paragraphs: [
      'Turned 15 vacant lots into productive gardens. All organic, all community-managed.',
      'Food sovereignty in a neighborhood that lost its last grocery store. We grow food, build community, teach skills. This is mutual aid in action.',
    ],
    upvotes: 789,
    previewImageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400',
    commentCount: 167,
  },
  {
    id: '21',
    username: 'neuroscience_phd',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 336).toISOString(),
    title: 'Mapped neural pathways that encode musical memory',
    paragraphs: [
      'Used fMRI to track how the brain processes and recalls music. Found unexpected connections to emotional regulation.',
      'This research could inform music therapy for Alzheimer patients. The brain and music relationship is more complex than we thought.',
    ],
    upvotes: 545,
    commentCount: 112,
  },
  {
    id: '22',
    username: 'architecture_collective',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 360).toISOString(),
    title: 'Built affordable housing using 3D-printed recycled plastic',
    paragraphs: [
      'Each house costs under $10,000 and can be printed in 48 hours. Using ocean plastic as building material.',
      'Piloting in Philippines after typhoon damage. Solving two problems: housing shortage and plastic pollution.',
    ],
    upvotes: 1678,
    previewImageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400',
    commentCount: 289,
  },
  {
    id: '23',
    username: 'classical_pianist_vienna',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 384).toISOString(),
    title: 'Premiered concerto written by AI trained on Bach',
    paragraphs: [
      'A neural network analyzed Bach chorales and composed a new piece. I performed the world premiere last night.',
      'The audience could not tell which movements were Bach and which were AI. This raises fascinating questions about creativity and authorship.',
    ],
    upvotes: 434,
    commentCount: 198,
  },
  {
    id: '24',
    username: 'water_engineer_ethiopia',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 408).toISOString(),
    title: 'Our fog-harvesting nets provide clean water to 10,000 people',
    paragraphs: [
      'In areas with no wells or rain, we capture moisture from morning fog using mesh nets.',
      'Simple technology, massive impact. Villagers no longer walk 6 hours for water. Children can attend school. Women have time for income-generating work.',
    ],
    upvotes: 1234,
    commentCount: 245,
  },
  {
    id: '25',
    username: 'graphic_novelist_montreal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 432).toISOString(),
    title: 'My graphic novel about immigration won the Eisner Award',
    paragraphs: [
      'Took 4 years to illustrate my family story of leaving Lebanon. Every panel is hand-drawn.',
      'The book is being translated into 12 languages. Stories like ours need to be told, especially now.',
    ],
    upvotes: 567,
    previewImageUrl: 'https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=400',
    commentCount: 89,
  },
  {
    id: '26',
    username: 'renewable_energy_pakistan',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 456).toISOString(),
    title: 'Solar microgrid powers entire valley without government grid',
    paragraphs: [
      'Remote mountain community pooled resources to install solar panels. Now have 24/7 electricity for first time.',
      'Schools can use computers. Clinic can refrigerate vaccines. Small businesses are starting. Energy independence changes everything.',
    ],
    upvotes: 923,
    commentCount: 178,
  },
  {
    id: '27',
    username: 'dance_choreographer_brazil',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 480).toISOString(),
    title: 'Created dance piece merging capoeira with contemporary ballet',
    paragraphs: [
      'Exploring Afro-Brazilian identity through movement. The piece premiered at São Paulo Dance Festival.',
      'Critics called it revolutionary. To me it is just honest. Our bodies hold history and create future simultaneously.',
    ],
    upvotes: 445,
    commentCount: 67,
  },
  {
    id: '28',
    username: 'cybersecurity_activist',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 504).toISOString(),
    title: 'Built encrypted messaging app used by journalists in 40 countries',
    paragraphs: [
      'Designed specifically for hostile environments. No phone number required, disappearing messages, decentralized architecture.',
      'Open source and free. Already helped expose corruption in 3 countries. Technology for press freedom.',
    ],
    upvotes: 1089,
    commentCount: 234,
  },
  {
    id: '29',
    username: 'literary_translator',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 528).toISOString(),
    title: 'Translated 50 overlooked women poets into English',
    paragraphs: [
      'Spent 10 years finding and translating poets from 25 languages. Many had never been published in English.',
      'University press released the anthology yesterday. These voices deserve to be heard beyond their linguistic borders.',
    ],
    upvotes: 378,
    commentCount: 92,
  },
  {
    id: '30',
    username: 'mycology_researcher',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 552).toISOString(),
    title: 'Mushroom-based packaging replacing Styrofoam in major retailers',
    paragraphs: [
      'Mycelium grows into any shape in days, then is heat-dried. Completely biodegradable and stronger than foam.',
      'Three major companies switching to our material. Fungi might save us from our plastic problem.',
    ],
    upvotes: 1567,
    previewImageUrl: 'https://images.unsplash.com/photo-1459156212016-c812468e2115?w=400',
    commentCount: 312,
  },
]
