import { WinProps } from '../components/WinCard'

export const sampleWins: WinProps['win'][] = [
  {
    id: '1',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    title: 'Prithvi Narayan Shah Divya Upadesh',
    paragraphs: [
      'After His Majesty captured the three cities of Nepal (Kathmandu, Lalitput and Bhaktapur) and the Hindupati Raja,l he went to Nuwakot for the last. He summoned his priests, teachers, household,4 family, nobles, and his tutor, Surath Singh Rana, and all the elders and spoke to them thus : When an old man dies, his words die with him, so they say. What vou who are gathered here will hear from me, pass on to your children, and they to ours; and this kingdom will endure.',
    ],
    upvotes: 342,
    previewImageUrl: '',
    commentCount: 78,
  },
  {
    id: '2',
    username: 'nepal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    title: 'When an old man dies, his word dies with him',
    paragraphs: [
      'So they say. What vou who are gathered here will hear from me, pass on to your children, and they to ours; and this kingdom will endure.',
    ],
    upvotes: 892,
    commentCount: 234,
  },
  {
    id: '3',
    username: 'street_photographer_tokyo',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    title: 'Won the Sony World Photography Award',
    paragraphs: [
      'Our mothers were three. Of three bridal chambers we brothers came, avatars of the Pandavs. Mv own marriage took place in Makwanpur. The bride was not given to me. I went to Makwanpur to take the bride and return by way of Nepal (Nepal pani dekhi bhani au bhani).',
    ],
    upvotes: 567,
    previewImageUrl: '',
    commentCount: 89,
  },
  {
    id: '4',
    username: 'climate_activist_kenya',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    title: 'Our reforestation project planted its millionth tree',
    paragraphs: [
      'Started with 20 volunteers in my village. Now we have 5,000 people across East Africa planting indigenous species.',
      'We are not just restoring ecosystems but creating jobs and teaching sustainable agriculture. This is how we fight climate change from the ground up.',
    ],
    upvotes: 1203,
    previewImageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400',
    commentCount: 156,
  },
  {
    id: '5',
    username: 'indie_game_dev',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    title: 'My solo-developed game hit 100k players on Steam',
    paragraphs: [
      'Spent 3 years in my apartment coding every night after my day job. Today we crossed 100,000 players.',
      'The reviews are 95 percent positive. People are connecting with the story about grief and healing. That was the whole point.',
    ],
    upvotes: 445,
    commentCount: 92,
  },
  {
    id: '6',
    username: 'biotech_founder_boston',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    title: 'FDA approved our gene therapy for sickle cell',
    paragraphs: [
      'After 8 years and 200 million in funding, we got the approval letter this morning. Our CRISPR treatment is going to patients.',
      'This could cure a disease that affects millions globally. The clinical trial results were beyond our best projections.',
    ],
    upvotes: 2341,
    commentCount: 412,
  },
  {
    id: '7',
    username: 'documentary_filmmaker',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    title: 'My film about ocean plastics is screening at Sundance',
    paragraphs: [
      'We followed ocean cleanup crews for 18 months across the Pacific. The footage is haunting but also hopeful.',
      'Three distributors are already interested. This issue needs more attention and I think we created something that will move people to act.',
    ],
    upvotes: 678,
    previewImageUrl: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400',
    commentCount: 134,
  },
  {
    id: '8',
    username: 'ai_ethics_researcher',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    title: 'Published framework for algorithmic accountability that EU is adopting',
    paragraphs: [
      'Our research team spent 2 years developing transparency standards for AI systems. The EU AI Act just incorporated our recommendations.',
      'This means companies will have to disclose how their algorithms make decisions that affect people. Real accountability is coming.',
    ],
    upvotes: 534,
    commentCount: 167,
  },
  {
    id: '9',
    username: 'ceramic_artist_seoul',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    title: 'My celadon pieces are in the National Museum collection',
    paragraphs: [
      'Spent 15 years studying traditional Korean pottery techniques. Three of my celadon vases were acquired by the museum.',
      'I use 12th century methods but create contemporary forms. Bridging past and present through clay.',
    ],
    upvotes: 289,
    previewImageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400',
    commentCount: 45,
  },
  {
    id: '10',
    username: 'refugee_advocate_berlin',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    title: 'Our legal aid clinic helped 1,000 refugees gain asylum',
    paragraphs: [
      'Started in a church basement with 3 volunteer lawyers. Now we have 30 staff and offices in 5 cities.',
      'Each case is a person rebuilding their life. We have won 87 percent of our cases. Justice is possible.',
    ],
    upvotes: 892,
    commentCount: 201,
  },
  {
    id: '11',
    username: 'ml_engineer_bangalore',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    title: 'Our open-source translation model works for 200 languages',
    paragraphs: [
      'Most AI research focuses on English. We trained a model that includes indigenous languages with limited digital text.',
      'Released everything under MIT license. Language preservation through technology. Communities are already using it to digitize oral histories.',
    ],
    upvotes: 743,
    commentCount: 178,
  },
  {
    id: '12',
    username: 'urban_planner_amsterdam',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    title: 'City approved my car-free neighborhood design',
    paragraphs: [
      'Took 4 years of community meetings and revisions. We are creating a 15-minute neighborhood where everything is walkable.',
      'Construction starts next month. This will be a model for other cities rethinking urban spaces around people instead of cars.',
    ],
    upvotes: 456,
    previewImageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400',
    commentCount: 98,
  },
  {
    id: '13',
    username: 'jazz_composer_new_orleans',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    title: 'My album blending jazz and West African rhythms won a Grammy',
    paragraphs: [
      'Spent 2 years in Senegal learning traditional drumming and collaborating with local musicians.',
      'This music is about diaspora and connection. The Grammy is validation but the real win was the creative journey and friendships formed.',
    ],
    upvotes: 512,
    commentCount: 87,
  },
  {
    id: '14',
    username: 'ocean_scientist_australia',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
    title: 'Discovered coral species that resists bleaching',
    paragraphs: [
      'After 200 dives mapping the Great Barrier Reef, we found colonies thriving in warming waters.',
      'Their genetic adaptation could be key to reef restoration. We are already testing propagation methods. There is still hope for our reefs.',
    ],
    upvotes: 1124,
    previewImageUrl: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400',
    commentCount: 267,
  },
  {
    id: '15',
    username: 'vr_designer_singapore',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(),
    title: 'Created VR therapy program that reduces PTSD symptoms by 60%',
    paragraphs: [
      'Worked with psychologists and veterans to design safe exposure therapy in virtual environments.',
      'Clinical trials showed better results than traditional methods. Now partnering with VA hospitals to scale this up.',
    ],
    upvotes: 678,
    commentCount: 143,
  },
  {
    id: '16',
    username: 'indigenous_language_teacher',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 216).toISOString(),
    title: 'First native speaker graduated from our language immersion program',
    paragraphs: [
      'My language had only 12 fluent speakers left. We started teaching children 5 years ago.',
      'Today our first student became fluent. She is 14 and already teaching her younger siblings. A language survives.',
    ],
    upvotes: 934,
    commentCount: 189,
  },
  {
    id: '17',
    username: 'space_engineer_mumbai',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 240).toISOString(),
    title: 'Our satellite constellation brings internet to remote villages',
    paragraphs: [
      'Launched the last of 48 satellites yesterday. Now covering regions where fiber optic is impossible.',
      '500 million people will gain internet access. Education and economic opportunity following connectivity.',
    ],
    upvotes: 1456,
    commentCount: 312,
  },
  {
    id: '18',
    username: 'textile_artist_ghana',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 264).toISOString(),
    title: 'My kente patterns are in Victoria and Albert Museum',
    paragraphs: [
      'Modern interpretations of traditional Ashanti weaving. Each pattern tells stories of resistance and resilience.',
      'The museum specifically wanted contemporary African voices. Our craft traditions are living art, not artifacts.',
    ],
    upvotes: 423,
    previewImageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400',
    commentCount: 76,
  },
  {
    id: '19',
    username: 'robotics_professor_zurich',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 288).toISOString(),
    title: 'Our soft robots can safely interact with marine life',
    paragraphs: [
      'Developed bio-inspired underwater drones that move like jellyfish. No propellers to harm wildlife.',
      'Already deployed to study deep sea creatures without disturbing them. Nature-inspired engineering at its best.',
    ],
    upvotes: 687,
    commentCount: 134,
  },
  {
    id: '20',
    username: 'community_organizer_detroit',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 312).toISOString(),
    title: 'Our urban farm collective feeds 2,000 families',
    paragraphs: [
      'Turned 15 vacant lots into productive gardens. All organic, all community-managed.',
      'Food sovereignty in a neighborhood that lost its last grocery store. We grow food, build community, teach skills. This is mutual aid in action.',
    ],
    upvotes: 789,
    previewImageUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400',
    commentCount: 167,
  },
  {
    id: '21',
    username: 'neuroscience_phd',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 336).toISOString(),
    title: 'Mapped neural pathways that encode musical memory',
    paragraphs: [
      'Used fMRI to track how the brain processes and recalls music. Found unexpected connections to emotional regulation.',
      'This research could inform music therapy for Alzheimer patients. The brain and music relationship is more complex than we thought.',
    ],
    upvotes: 545,
    commentCount: 112,
  },
  {
    id: '22',
    username: 'architecture_collective',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 360).toISOString(),
    title: 'Built affordable housing using 3D-printed recycled plastic',
    paragraphs: [
      'Each house costs under $10,000 and can be printed in 48 hours. Using ocean plastic as building material.',
      'Piloting in Philippines after typhoon damage. Solving two problems: housing shortage and plastic pollution.',
    ],
    upvotes: 1678,
    previewImageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=400',
    commentCount: 289,
  },
  {
    id: '23',
    username: 'classical_pianist_vienna',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 384).toISOString(),
    title: 'Premiered concerto written by AI trained on Bach',
    paragraphs: [
      'A neural network analyzed Bach chorales and composed a new piece. I performed the world premiere last night.',
      'The audience could not tell which movements were Bach and which were AI. This raises fascinating questions about creativity and authorship.',
    ],
    upvotes: 434,
    commentCount: 198,
  },
  {
    id: '24',
    username: 'water_engineer_ethiopia',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 408).toISOString(),
    title: 'Our fog-harvesting nets provide clean water to 10,000 people',
    paragraphs: [
      'In areas with no wells or rain, we capture moisture from morning fog using mesh nets.',
      'Simple technology, massive impact. Villagers no longer walk 6 hours for water. Children can attend school. Women have time for income-generating work.',
    ],
    upvotes: 1234,
    commentCount: 245,
  },
  {
    id: '25',
    username: 'graphic_novelist_montreal',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 432).toISOString(),
    title: 'My graphic novel about immigration won the Eisner Award',
    paragraphs: [
      'Took 4 years to illustrate my family story of leaving Lebanon. Every panel is hand-drawn.',
      'The book is being translated into 12 languages. Stories like ours need to be told, especially now.',
    ],
    upvotes: 567,
    previewImageUrl: 'https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=400',
    commentCount: 89,
  },
  {
    id: '26',
    username: 'renewable_energy_pakistan',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 456).toISOString(),
    title: 'Solar microgrid powers entire valley without government grid',
    paragraphs: [
      'Remote mountain community pooled resources to install solar panels. Now have 24/7 electricity for first time.',
      'Schools can use computers. Clinic can refrigerate vaccines. Small businesses are starting. Energy independence changes everything.',
    ],
    upvotes: 923,
    commentCount: 178,
  },
  {
    id: '27',
    username: 'dance_choreographer_brazil',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 480).toISOString(),
    title: 'Created dance piece merging capoeira with contemporary ballet',
    paragraphs: [
      'Exploring Afro-Brazilian identity through movement. The piece premiered at São Paulo Dance Festival.',
      'Critics called it revolutionary. To me it is just honest. Our bodies hold history and create future simultaneously.',
    ],
    upvotes: 445,
    commentCount: 67,
  },
  {
    id: '28',
    username: 'cybersecurity_activist',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 504).toISOString(),
    title: 'Built encrypted messaging app used by journalists in 40 countries',
    paragraphs: [
      'Designed specifically for hostile environments. No phone number required, disappearing messages, decentralized architecture.',
      'Open source and free. Already helped expose corruption in 3 countries. Technology for press freedom.',
    ],
    upvotes: 1089,
    commentCount: 234,
  },
  {
    id: '29',
    username: 'literary_translator',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 528).toISOString(),
    title: 'Translated 50 overlooked women poets into English',
    paragraphs: [
      'Spent 10 years finding and translating poets from 25 languages. Many had never been published in English.',
      'University press released the anthology yesterday. These voices deserve to be heard beyond their linguistic borders.',
    ],
    upvotes: 378,
    commentCount: 92,
  },
  {
    id: '30',
    username: 'mycology_researcher',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 552).toISOString(),
    title: 'Mushroom-based packaging replacing Styrofoam in major retailers',
    paragraphs: [
      'Mycelium grows into any shape in days, then is heat-dried. Completely biodegradable and stronger than foam.',
      'Three major companies switching to our material. Fungi might save us from our plastic problem.',
    ],
    upvotes: 1567,
    previewImageUrl: 'https://images.unsplash.com/photo-1459156212016-c812468e2115?w=400',
    commentCount: 312,
  },
]
